const StudentsActionType = {
  FETCHING_ALL_STUDENTS: "FETCHING_ALL_STUDENTS",
  FETCH_SINGLE_STUDENT: 'FETCH_SINGLE_STUDENT',
  CREATING_STUDENT: 'CREATING_STUDENT', 
  EDITING_STUDENT: "UPDATING_STUDENT", 
  DELETING_STUDENT: "DELETING_STUDENT"
};

export default StudentsActionType;
