const CampusesActionType = {
  FETCHING_ALL_CAMPUSES: "FETCHING_ALL_CAMPUSES",
  FETCHING_SINGLE_CAMPUS: "FETCHING_SINGLE_CAMPUS", 
  CREATING_CAMPUS: 'CREATING_CAMPUS'
};

export default CampusesActionType;
